[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "EbccWrapper"
version = "0.1"

[tool.setuptools.packages.find]
include = ["ebcc_wrapper"]
